server:
  port: 8181
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pagination
    username: pagination
    password: pagination
  jpa:
    open-in-view: false
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml

logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG